### ISSUE TITLE
Upgraded from 1.1.0 to 1.2.0, creates a panic in Clauses:27

### ISSUE THREAD

**Issue by mrz1836** [go-gorm/dbresolver#71]
Here is the line where it fails. We are currently using GORM in bux: https://github.com/BuxOrg/bux

We just recently upgraded this package and now it is failing in the Query() method : `stmt.DB.Callback().Query().Get("gorm:db_resolver")(stmt.DB)`
```
goroutine 8906 [running]:
testing.tRunner.func1.2({0x184d840, 0x2b6ceb0})
	/opt/hostedtoolcache/go/1.17.9/x64/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.17.9/x64/src/testing/testing.go:1212 +0x218
panic({0x184d840, 0x2b6ceb0})
	/opt/hostedtoolcache/go/1.17.9/x64/src/runtime/panic.go:1038 +0x215
gorm.io/plugin/dbresolver.Operation.ModifyStatement({0x1a74da3, 0xc000f1d801}, 0xc000f1dc00)
	/home/runner/go/pkg/mod/gorm.io/plugin/dbresolver@v1.2.0/clauses.go:27 +0x1c6
gorm.io/gorm.(*DB).Clauses(0x1ee0850, {0xc000e9da50, 0x1, 0x18d0120})
	/home/runner/go/pkg/mod/gorm.io/gorm@v1.23.5/chainable_api.go:32 +0x24f
```

Additional Outputs from Debugging:

<img width="886" alt="Screen Shot 2022-05-02 at 9 23 53 AM" src="https://user-images.githubusercontent.com/3743002/166241113-280a75f6-d1dc-428e-a929-1d194897ffcb.png">

<img width="1116" alt="Screen Shot 2022-05-02 at 9 24 11 AM" src="https://user-images.githubusercontent.com/3743002/166241134-342125fb-9be1-4ed6-9d80-fa1f53791d4c.png">

<img width="459" alt="Screen Shot 2022-05-02 at 9 19 52 AM" src="https://user-images.githubusercontent.com/3743002/166240403-b69925c0-4fcf-4c60-b2f9-0747eebfc6e2.png">

<img width="1004" alt="Screen Shot 2022-05-02 at 9 19 58 AM" src="https://user-images.githubusercontent.com/3743002/166240443-c8d88c4a-5f82-4557-9cd5-87dd8e3ffec4.png">

<img width="1253" alt="Screen Shot 2022-05-02 at 9 24 37 AM" src="https://user-images.githubusercontent.com/3743002/166241146-d8089437-a308-4e18-a3e7-76e4fd9636ef.png">

**Comment by jinzhu** [comment]
Have you initialized dbresolver?

```go
DB.Use(dbresolver.Register(dbresolver.Config{
```

**Comment by mrz1836** [comment]
I believe so - check this line... Am I doing it correctly...?
https://github.com/BuxOrg/bux/blob/100a48becd6b69f69eb10ab1b0c411603f938415/datastore/sql.go#L117

<img width="683" alt="Screen Shot 2022-05-02 at 9 43 27 AM" src="https://user-images.githubusercontent.com/3743002/166244061-ae234cbc-0c7a-4801-ab32-7709a5645bb5.png">

**Comment by jinzhu** [comment]
Can you debug this, does `dbresolver`'s `registerCallbacks` method called for the `db`? from the panic message, seems like a bug in your code...

**Comment by mrz1836** [comment]
`stmt.DB.Callback().Query().Get("gorm:db_resolver")` returns nil, hence then trying to make it a type is failing as it is nil

`stmt.DB.Callback().Query().Get("gorm:db_resolver")(stmt.DB)`

`gorm:db_resolver` is missing... hmm

I will debug further.

**Comment by mrz1836** [comment]
Thank you - that helped! I fixed the issue ;-)
